### ISSUE TITLE
VanillaJS examples?

### ISSUE THREAD

**Issue by stela5** [eclifford/bronson#4]
Any chance you could include plain vanilla javascript examples on http://bronsonjs.com/ and http://bronsonjs.com/reference.html?  It may be helpful for those who don't use CoffeeScript or aren't familiar with that syntax.

Also, when I left-click on the map on http://bronsonjs.com/demo.html the Google Maps block turns pure blue and the Tweets block goes blank (tried on the latest IE, Firefox and Chrome)

**Comment by hershmire** [comment]
An easy way to remedy this is to just go to http://js2coffee.org/, click on the "Coffee > JS" tab, and past in any valid CoffeeScript syntax in the left column. That will give you the JS translation you're looking for.

**Comment by stela5** [comment]
Thanks for the tip.  I actually attempted to use that very website while reviewing your examples, but the differences in whitespace when copying and pasting your code would almost always throw errors (e.g. "Error: Parse error on line 8: Unexpected 'INDENT'").  Also, human-generated code is always shorter and more readable than computer-generated code intended for JavaScript parsing engines.

Either way, thanks for the library and if I create some JavaScript equivalents during my testing I'll pass them on.
